//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 01:02:39 PM ICT 
//


package xyz.un4ckn0wl3z.genmejaxb.demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CardStatusBankResult">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardStatusBankResult"
})
@XmlRootElement(name = "CardStatusBankResponse", namespace = "http://tempuri.org/")
public class CardStatusBankResponse {

    @XmlElement(name = "CardStatusBankResult", namespace = "http://tempuri.org/", required = true)
    protected CardStatusBankResponse.CardStatusBankResult cardStatusBankResult;

    /**
     * Gets the value of the cardStatusBankResult property.
     * 
     * @return
     *     possible object is
     *     {@link CardStatusBankResponse.CardStatusBankResult }
     *     
     */
    public CardStatusBankResponse.CardStatusBankResult getCardStatusBankResult() {
        return cardStatusBankResult;
    }

    /**
     * Sets the value of the cardStatusBankResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardStatusBankResponse.CardStatusBankResult }
     *     
     */
    public void setCardStatusBankResult(CardStatusBankResponse.CardStatusBankResult value) {
        this.cardStatusBankResult = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "code",
        "desc"
    })
    public static class CardStatusBankResult {

        @XmlElement(name = "Code", namespace = "http://tempuri.org/")
        protected int code;
        @XmlElement(name = "Desc", namespace = "http://tempuri.org/", required = true)
        protected String desc;

        /**
         * Gets the value of the code property.
         * 
         */
        public int getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         */
        public void setCode(int value) {
            this.code = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

		@Override
		public String toString() {
			return "CardStatusBankResult [code=" + code + ", desc=" + desc
					+ "]";
		}
        
        

    }


	@Override
	public String toString() {
		return "CardStatusBankResponse [cardStatusBankResult="
				+ cardStatusBankResult + "]";
	}
    
    

}
